ALTER TABLE `eachbb_member`.`lastest_news` MODIFY COLUMN `id` INT(10) UNSIGNED NOT NULL,
 MODIFY COLUMN `photo` VARCHAR(128) CHARACTER SET utf8 COLLATE utf8_general_ci,
 MODIFY COLUMN `f_id` INTEGER(11) UNSIGNED DEFAULT NULL
, ROW_FORMAT = DYNAMIC;
