ALTER TABLE `eachbb_member`.`photo` MODIFY COLUMN `comment_count` INTEGER DEFAULT 0,
 MODIFY COLUMN `visit_count` INTEGER DEFAULT 0,
 MODIFY COLUMN `ip` VARCHAR(128) CHARACTER SET utf8 COLLATE utf8_general_ci,
 MODIFY COLUMN `height` INTEGER,
 MODIFY COLUMN `title` VARCHAR(256) CHARACTER SET utf8 COLLATE utf8_general_ci;