CREATE DATABASE IF NOT EXISTS eachbb_member;
CREATE TABLE  `eachbb_member`.`member` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `password` varchar(50) NOT NULL,
  `email` varchar(50) DEFAULT NULL,
  `authenticated` int(11) NOT NULL DEFAULT '0',
  `authenticate_string` char(20) DEFAULT '',
  `created_at` datetime NOT NULL,
  `last_login` datetime NOT NULL,
  `authenticated_at` datetime NOT NULL,
  `avatar` varchar(256) NOT NULL,
  `uid` int(11) DEFAULT '0',
  `cache_name` char(20) DEFAULT NULL,
  `baby_status` int(11) NOT NULL DEFAULT '0' COMMENT '是否怀孕，1是已经怀孕，2是未怀孕，3是怀孕中',
  `baby_birthday` datetime DEFAULT NULL COMMENT '宝宝生日',
  `birthday` datetime DEFAULT NULL COMMENT '注册人生日',
  `zip` varchar(50) DEFAULT NULL COMMENT '邮编',
  `phone` varchar(50) DEFAULT NULL COMMENT '联系电话',
  `address` varchar(256) NOT NULL COMMENT '住址',
  `baby_name` varchar(256) DEFAULT NULL COMMENT '宝宝姓名',
  `baby_gender` int(11) DEFAULT NULL COMMENT '宝宝性别，1是男孩，2是女孩',
  `gender` int(11) NOT NULL DEFAULT '0' COMMENT '性别，1是男性，2是女性',
  `ip` varchar(50) DEFAULT NULL,
  `fix_phone` varchar(50) DEFAULT NULL COMMENT '固定电话',
  `id_num` varchar(20) DEFAULT NULL COMMENT '身份证号',
  `education` varchar(50) DEFAULT NULL COMMENT '教育程度',
  `industry` varchar(100) DEFAULT NULL COMMENT '行业',
  `income` varchar(50) DEFAULT NULL COMMENT '家庭月收入',
  `register_phone` varchar(50) DEFAULT NULL COMMENT '注册手机',
  `true_name` varchar(50) DEFAULT NULL COMMENT '真实姓名',
  PRIMARY KEY (`id`)
)
